### ISSUE TITLE
[suggestion] item condition for hud

### ISSUE THREAD

**Issue by Biviho** [acherlin/Parasites-Addon-OverLast#1]
hi, i wanted to give a suggestion about the mod:

the ability to see the hud only when a specific item is held or in inventory, for example with the clock provided by parasite mod

this could be useful for avoiding unnecessary clutter in hud or to not have an additional keybind to remember

**Comment by acherlin** [comment]
The recommendations of issue were taken!
Please download overlast-1.12.2-0.1.1.jar in the curseforge.
Don't forget to star me, thanks.
