### ISSUE TITLE
No crafting recipes for specimen

### ISSUE THREAD

**Issue by dariostrm** [acherlin/Parasites-Addon-OverLast#10]
I got very hyped about the final battle and wanted to try it in my world so I read the whole wiki to find out how it works but it isn't stated in the wiki how to obtain the world purification core or the specimen. The mod Just Enough Items also doesn't show any recipe. I found the recipes in the config file but they don't seem to work or are impossible to craft. 
For example:
```
Agricultural Specimen Recipe.(eg: minecraft:id;amount;meta)
    S:specimenFarm <
        overlast:crops;640;0
        minecraft:pumpkin;192;0
     >
```
So you need 10 stacks of crop boxes and 3 stacks of pumpkins to craft this, but that can't even fit into the crafting table.
So how do you obtain a world purification core to start a final battle?
Even if it may still be impossible because it's being worked on, you should write this in the wiki or somewhere at least.
Anyways, the mod is awesome! Thanks!

**Comment by acherlin** [comment]
This MOD was originally designed for a modpack, with the idea that players would work together to complete the Final Battle. Traditional 3x3 crafting recipes would require too many intermediate products, which was too cumbersome. Therefore, we chose to borrow the workbench from another MOD in the same modpack to complete this design. If you have installed MrCrayfish's Gun Mod, you can use the Workbench to craft the Special Block. If you don't want to install it, you can also create a recipe in ftbquest.
