### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by Water-OR** [acherlin/Parasites-Addon-OverLast#12]
期待能有更多、更详细的配置，比如理智的一些细节调整比如说在地狱/夏天穿配置中置顶的盔甲或者饰品就可以免疫因为热而导致的扣血之类，以及对于一些其他演化阶段（比如-1阶段与-2阶段的调整）。初始季节似乎被固定在了秋季（？）这也可以增加一个配置

**Comment by acherlin** [comment]
最新版本已经修复
