### ISSUE TITLE
Issue with Buglins and Open Modular Turrets

### ISSUE THREAD

**Issue by Cyakat** [acherlin/Parasites-Addon-OverLast#14]
This happens everytime a buglin is killed by a gun turret as far as I have tested.
This doesn't happen with other SRP creatures
[crash-2024-01-17_20.04.58-server.txt](https://github.com/acherlin/Parasites-Addon-OverLast/files/13971695/crash-2024-01-17_20.04.58-server.txt)

**Comment by Cyakat** [comment]
This has also happened with moving flesh piles

**Comment by acherlin** [comment]
I should have fixed this issue, but I haven't uploaded the latest version to CurseForge. If the issue still persists in version 0.2.9B7, please provide me with timely feedback.

**Comment by Cyakat** [comment]
I apologize for the late reply but i am still experiencing this issue
[crash-2024-01-30_23.53.21-server.txt](https://github.com/acherlin/Parasites-Addon-OverLast/files/14105576/crash-2024-01-30_23.53.21-server.txt)
Maybe it is on the OMT side. I'm not too sure.

**Comment by Cyakat** [comment]
Can confirm that this is solved now
