### ISSUE TITLE
Many recipes and an item are missing

### ISSUE THREAD

**Issue by Mdbgamer** [acherlin/Parasites-Addon-OverLast#2]
Scythe core is gone(which is probably what is breaking all these recipes)

All Invasive Compound weapons
Rupter Labrys
Heart Rapier
Flesh Eater
Yellow Halberd
Living Helmet and Chestplate
Shellbreaker
Longarms Saber
And Pestilent Scythe and Scythe Core Block(obviously :P)
Have no crafting recipes.

Hope to see a response or an update relatively soon fixing these. I'd imagine it was a fluke and the scythe core got removed by accident/it was removed for a reason and wasn't replaced in the other recipes. 

In the meantime, though less immediately and not wholly important, perhaps Tinker's Armory support for the resources? It'd be a neat thing to have, if it doesn't already exist.

**Comment by Mdbgamer** [comment]
Correction: Apparently there's a scythe handle item, and that's missing too.

**Comment by acherlin** [comment]
Sorry, you should go to another project and raise issue. (This project is Parasites Addon : OverLast and not Scape and Run: Parasites Addon by NoCube)

**Comment by Mdbgamer** [comment]
Ah, sorry!
