### ISSUE TITLE
Crash out of the blue

### ISSUE THREAD

**Issue by Hamsterpouch** [acherlin/Parasites-Addon-OverLast#3]
[crash-2022-04-19_12.28.08-server.txt](https://github.com/acherlin/Parasites-Addon-OverLast/files/8515181/crash-2022-04-19_12.28.08-server.txt)
I was just playing around, and the game crashed with this report.

**Comment by acherlin** [comment]
You should use version 0.1.3 or later. Version 0.1.1 only supports SRP V1.9.1.
