### ISSUE TITLE
Stop applying Absorpsion randomly.

### ISSUE THREAD

**Issue by MagmaSlime123** [acherlin/Parasites-Addon-OverLast#5]
Title.

Stop applying the Absorpsion potion effect randomly. Happens with or without other mods.

Also, please let the Temp and Evolution bar positions be configured separately.

**Comment by dariostrm** [comment]
The Absorption effect isn't applied randomly. It's applied due to the [Courage mechanic](https://github.com/acherlin/Parasites-Addon-OverLast/wiki/Courage). You can turn the courage mechanic off in the config file - enableCourage=false
