### ISSUE TITLE
Making my parasites burn in the sun

### ISSUE THREAD

**Issue by Neocat18** [acherlin/Parasites-Addon-OverLast#6]
I was playing in creative mode, minding my own business, when I noticed the rupters started burning. I've started turning off my mods, trying to find out what is causing it, and it turns out it was this one. I even turned off all of mods besides this one and the main parasites one, and it's still burning. And no, they aren't walking into lava.

I can try a new save with just this one and scape and run to see if anything changes. And if it does, I can let you guys know. Thanks.

**Comment by acherlin** [comment]
Please consult the wiki. [https://github.com/acherlin/Parasites-Addon-OverLast/wiki/Season](https://github.com/acherlin/Parasites-Addon-OverLast/wiki/Season)

**Comment by dariostrm** [comment]
Parasites burn in summer. That's a feature of this mod
