### ISSUE TITLE
进入OTG世界时崩溃

### ISSUE THREAD

**Issue by strongberg** [acherlin/Parasites-Addon-OverLast#8]
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Parasites Addon : OverLast (overlast)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 113
    at com.overlast.season.modifier.BiomeTempController.getOriginalTemperature(BiomeTempController.java:84)
    at com.overlast.season.modifier.BiomeTempController.changeBiomeTemperatures(BiomeTempController.java:112)
    at com.overlast.season.WorldSeason.getSeasonData(WorldSeason.java:122)
    at com.overlast.util.WorldDataMgr.loadFromDisk(WorldDataMgr.java:35)
    at com.overlast.CommonProxy.serverStarted(CommonProxy.java:111)
    at com.overlast.OverLast.serverStarted(OverLast.java:64)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.GeneratedMethodAccessor115.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:804)
    at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:302)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:488)
    at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_351, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 5256606920 bytes (5013 MB) / 8388608000 bytes (8000 MB) up to 8388608000 bytes (8000 MB)
  JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx8000m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
  FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_E3 132 mods loaded, 132 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State   | ID                            | Version              | Source                                                      | Signature                                |
       |:------- |:----------------------------- |:-------------------- |:----------------------------------------------------------- |:---------------------------------------- |
       | LCHIJA  | minecraft                     | 1.12.2               | minecraft.jar                                               | None                                     |
       | LCHIJA  | mcp                           | 9.42                 | minecraft.jar                                               | None                                     |
       | LCHIJA  | FML                           | 8.0.99.99            | forge-1.12.2-14.23.5.2860.jar                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA  | forge                         | 14.23.5.2860         | forge-1.12.2-14.23.5.2860.jar                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA  | jecharacters                  | 1.12.0-3.4.7         | [辅助-jei附属-拼音搜索]JustEnoughCharacters-1.12.0-3.4.7.jar        | None                                     |
       | LCHIJA  | otgcore                       | 1.12.2-v9.4          | minecraft.jar                                               | None                                     |
       | LCHIJA  | smoothfontcore                | mc1.12.2-2.1.4       | minecraft.jar                                               | None                                     |
       | LCHIJA  | mixinbooter                   | 7.0                  | minecraft.jar                                               | None                                     |
       | LCHIJA  | foamfixcore                   | 7.7.4                | minecraft.jar                                               | None                                     |
       | LCHIJA  | biometweakercore              | 1.0.39               | minecraft.jar                                               | None                                     |
       | LCHIJA  | smoothfont                    | mc1.12.2-2.1.4       | SmoothFont-mc1.12.2-2.1.4.jar                               | None                                     |
       | LCHIJA  | jei                           | 4.15.0.289           | jei_1.12.2-4.15.0.289.jar                                   | None                                     |
       | LCHIJA  | ftblib                        | 5.4.7.2              | [FTB Library（旧版）] FTBLib-5.4.7.2.jar                        | None                                     |
       | LCHIJA  | bookshelf                     | 2.3.590              | [lib]Bookshelf-1.12.2-2.3.590.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA  | crafttweaker                  | 4.1.20               | [魔改]CraftTweaker2-1.12-4.1.20.574.jar                       | None                                     |
       | LCHIJA  | cfm                           | 6.3.0                | [MrCrayfish 的家具] furniture-6.3.2-1.12.2.jar                 | None                                     |
       | LCHIJA  | aireducer                     | 0.3.0                | [优化]AIReducer-1.12.2-0.3.0.jar                              | None                                     |
       | LCHIJA  | drones                        | 0.3.1                | [优化]Drones-0.3.1.jar                                        | None                                     |
       | LCHIJA  | fat_cat                       | 0.0.5                | [优化]FatCat-0.0.5.jar                                        | None                                     |
       | LCHIJA  | foamfix                       | @VERSION@            | [优化]foamfix-0.10.15-1.12.2.jar                              | None                                     |
       | LCHIJA  | torohealthmod                 | 1.12.2-11            | [伤害显示] torohealth-1.12.2-11.jar                             | None                                     |
       | LCHIJA  | thesdtmfix                    | 1.0.0                | [修复]7_days_to_fix-1.0.0.jar                                 | None                                     |
       | LCHIJA  | sevendaystomine               | 1.12.2-1.0.2.10      | [冒险]sevendaystomine-1.12.2-1.0.2.10 .jar                    | None                                     |
       | LCHIJA  | dtmintegrations               | 1.5.1                | [修复]DTMIntegrations-1.12.2-1.5.1.jar                        | None                                     |
       | LCHIJA  | llibrary                      | 1.7.20               | llibrary-1.7.20-1.12.2.jar                                  | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA  | fossil                        | 8.0.5                | [冒险]fossilsarcheology-8.0.6.jar                             | None                                     |
       | LCHIJA  | srparasites                   | 1.9.4                | [冒险]SRParasites-1.12.2v1.9.5.jar                            | None                                     |
       | LCHIJA  | lostcities                    | 2.0.22               | [结构]lostcities-1.12-2.0.22.jar                              | None                                     |
       | LCHIJAE | overlast                      | 0.2.6                | [冒险]overlast-1.12.2-0.2.6.jar                               | None                                     |
       | LCHIJA  | deconstruction                | 3.0.4                | [分解台 T]DeconTable-3.0.4.jar                                 | None                                     |
       | LCHIJA  | aroma1997core                 | 2.0.0.2              | [前置]Aroma1997Core-1.12.2-2.0.0.2.jar                        | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | LCHIJA  | bnbgaminglib                  | 2.17.6               | [前置]BNBGamingLib-1.12.2-2.17.6.jar                          | None                                     |
       | LCHIJA  | redstoneflux                  | 2.1.1                | [前置]RedstoneFlux-1.12-2.1.1.1-universal.jar                 | None                                     |
       | LCHIJA  | cofhcore                      | 4.6.6                | [前置]CoFHCore-1.12.2-4.6.6.1-universal.jar                   | None                                     |
       | LCHIJA  | hammercore                    | 2.0.6.32             | [前置]HammerLib-1.12.2-2.0.6.32.jar                           | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCHIJA  | ichunutil                     | 7.2.1                | [前置]iChunUtil-1.12.2-7.2.1.jar                              | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA  | torcherino                    | 7.6                  | [加速火把] torcherino-7.6.jar                                   | None                                     |
       | LCHIJA  | dynamiclights                 | 1.4.9                | [动态光源]DynamicLights-1.12.2.jar                              | None                                     |
       | LCHIJA  | dynamiclights_onfire          | 1.0.7                | [动态光源]DynamicLights-1.12.2.jar                              | None                                     |
       | LCHIJA  | dynamiclights_creepers        | 1.0.6                | [动态光源]DynamicLights-1.12.2.jar                              | None                                     |
       | LCHIJA  | dynamiclights_dropitems       | 1.1.0                | [动态光源]DynamicLights-1.12.2.jar                              | None                                     |
       | LCHIJA  | dynamiclights_entityclasses   | 1.0.1                | [动态光源]DynamicLights-1.12.2.jar                              | None                                     |
       | LCHIJA  | dynamiclights_mobequipment    | 1.1.0                | [动态光源]DynamicLights-1.12.2.jar                              | None                                     |
       | LCHIJA  | dynamiclights_flamearrows     | 1.0.1                | [动态光源]DynamicLights-1.12.2.jar                              | None                                     |
       | LCHIJA  | dynamiclights_floodlights     | 1.0.3                | [动态光源]DynamicLights-1.12.2.jar                              | None                                     |
       | LCHIJA  | dynamiclights_otherplayers    | 1.0.9                | [动态光源]DynamicLights-1.12.2.jar                              | None                                     |
       | LCHIJA  | dynamiclights_theplayer       | 1.1.3                | [动态光源]DynamicLights-1.12.2.jar                              | None                                     |
       | LCHIJA  | avaritiarecipemaker           | 1.0.0                | [可视化无尽配方编辑器] avaritiarecipemaker-1.0.0.jar                  | None                                     |
       | LCHIJA  | gamestages                    | 2.0.115              | [魔改]GameStages-1.12.2-2.0.115.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA  | recipestages                  | 1.1.3                | [合成阶段]RecipeStages-1.1.3.jar                                | None                                     |
       | LCHIJA  | aromabackup                   | 2.1.1.4              | [存档]AromaBackup-1.12.2-2.1.1.4.jar                          | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | LCHIJA  | aromabackuprecovery           | 2.1.1.4              | [存档]AromaBackup-1.12.2-2.1.1.4.jar                          | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | LCHIJA  | testdummy                     | 1.12                 | [实用-稻草人]MmmMmmMmmMmm-1.12-1.14.jar                          | None                                     |
       | LCHIJA  | gravestone                    | 1.10.3               | [实用]gravestone-1.10.3.jar                                   | None                                     |
       | LCHIJA  | homingexporbs                 | 1.1                  | [实用]HomingExpOrbs-1.1.jar                                   | None                                     |
       | LCHIJA  | waila                         | 1.8.26               | [实用]Hwyla-1.8.26-B41_1.12.2.jar                             | None                                     |
       | LCHIJA  | improvableskills              | 12.4.68              | [实用]ImprovableSkills-1.12.2-12.4.68.jar                     | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCHIJA  | multimine                     | 1.6.2                | [实用]MultiMine-1.12.2.jar                                    | None                                     |
       | LCHIJA  | naturescompass                | 1.8.0                | [实用]NaturesCompass-1.12.2-1.8.0.jar                         | None                                     |
       | LCHIJA  | trashslot                     | 8.4.10               | [实用]TrashSlot_1.12.2-8.4.10.jar                             | None                                     |
       | LCHIJA  | journeymap                    | 1.12.2-5.7.1         | [旅行地图]journeymap-1.12.2-5.7.1.jar                           | None                                     |
       | LCHIJA  | travelersbackpack             | 1.0.35               | [旅行者背包] TravelersBackpack-1.12.2-1.0.35.jar                 | None                                     |
       | LCHIJA  | ironchest                     | 1.12.2-7.0.67.844    | [更多箱子]ironchest-1.12.2-7.0.72.847.jar                       | None                                     |
       | LCHIJA  | betterbuilderswands           | 0.13.2               | [更好的建筑之杖] BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar | None                                     |
       | LCHIJA  | animalium                     | 0.3.8                | [生物]Animalium-0.3.8.jar                                     | None                                     |
       | LCHIJA  | creepypastacraft              | 2                    | [生物]CreepyPastaCraft_Reborn_V2c-1.12.2-hotfix1.jar          | None                                     |
       | LCHIJA  | doggytalents                  | 1.15.1.6             | [生物]DoggyTalents-1.12.2-1.15.1.6.jar                        | None                                     |
       | LCHIJA  | lcrdrfs                       | 2.0.0                | [生物]LaserCreeperRobotDinoRidersFromSpace-2.0.0.jar          | None                                     |
       | LCHIJA  | patchouli                     | 1.0-21               | Patchouli-1.0-21.jar                                        | None                                     |
       | LCHIJA  | lepidodendron                 | 52.04                | [生物]lepidodendron-1.12.2-52.04.jar                          | None                                     |
       | LCHIJA  | shincolle                     | 1.12.2.1.0           | [生物]ShinColle-1.12.2.1.3-N.jar                              | None                                     |
       | LCHIJA  | armourers_workshop            | 1.12.2-0.50.5        | [皮肤]Armourers-Workshop-1.12.2-0.50.5.jar                    | None                                     |
       | LCHIJA  | customskinloader              | 14.9                 | [皮肤]CustomSkinLoader_Forge-14.9.jar                         | None                                     |
       | LCHIJA  | oreexcavation                 | 1.4.150              | [矿石挖掘] OreExcavation-1.4.150.jar                            | None                                     |
       | LCHIJA  | mekanism                      | 1.12.2-9.8.3.390     | [科技]Mekanism-1.12.2-9.8.3.390.jar                           | None                                     |
       | LCHIJA  | mekanismgenerators            | 1.12.2-9.8.3.390     | [科技-MEK]MekanismGenerators-1.12.2-9.8.3.390.jar             | None                                     |
       | LCHIJA  | codechickenlib                | 3.2.3.358            | [鸡块核心]CodeChickenLib-1.12.2-3.2.3.358-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA  | avaritia                      | 3.3.0                | [科技-无尽]Avaritia-1.12.2-3.3.0.33-universal.jar               | None                                     |
       | LCHIJA  | biotechnik                    | 1.0.1                | [科技-杀生电]BioTechnik-1.0.1.jar                                | None                                     |
       | LCHIJA  | fartgen                       | 1.1.0                | [科技-牛屁发电]cowgen-1.1.0.jar                                   | None                                     |
       | LCHIJA  | cookingforblockheads          | 6.5.0                | [科技]CookingForBlockheads_1.12.2-6.5.0.jar                   | None                                     |
       | LCHIJA  | cyberware                     | 0.2.11.29            | [科技]cyberware-1.12.2-0.2.11.29.jar                          | None                                     |
       | LCHIJA  | hbm                           | hbm-1.6.9A-1.12.2    | [科技]hbm-1.6.9a-G.jar                                        | None                                     |
       | LCHIJA  | rewired                       | 1.12.2               | [科技]ReWIRED-1.0.9b.jar                                      | None                                     |
       | LCHIJA  | stg                           | 1.12.2-1.2.3         | [穿草攻击] stg-1.12.2-1.2.3.jar                                 | None                                     |
       | LCHIJA  | mobbottle                     | 0.6                  | [装饰-生物瓶]MobBottle-0.6.jar                                   | None                                     |
       | LCHIJA  | bibliocraft                   | 2.4.6                | [装饰]BiblioCraft[v2.4.6][MC1.12.2].jar                       | None                                     |
       | LCHIJA  | googlyeyes                    | 7.1.1                | [装饰]GooglyEyes-1.12.2-7.1.1.jar                             | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA  | jetif                         | 1.4.1                | [辅助-jei流体支持-附属]jetif-1.12.2-1.4.1.jar                       | None                                     |
       | LCHIJA  | cofhworld                     | 1.4.0                | [魔改]CoFHWorld-1.12.2-1.4.0.1-universal.jar                  | None                                     |
       | LCHIJA  | ctgui                         | 1.0.0                | [魔改]CraftTweaker2-1.12-4.1.20.574.jar                       | None                                     |
       | LCHIJA  | crafttweakerjei               | 2.0.3                | [魔改]CraftTweaker2-1.12-4.1.20.574.jar                       | None                                     |
       | LCHIJA  | crafttweakersync              | 1.0                  | [魔改]CraftTweakerSync(CT脚本同步)-1.0.jar                        | None                                     |
       | LCHIJA  | itemfilters                   | 1.0.4.2              | ItemFilters-1.0.4.2.jar                                     | None                                     |
       | LCHIJA  | ftbquests                     | 1202.9.0.15          | [魔改]FTBQuests-1202.9.0.15.jar                               | None                                     |
       | LCHIJA  | incontrol                     | 3.9.18               | [魔改]incontrol-1.12-3.9.18.jar                               | None                                     |
       | LCHIJA  | itemstages                    | 2.0.49               | [魔改]ItemStages-1.12.2-2.0.49.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA  | materialchanger               | 1.0                  | [魔改]materialchanger1.0.3-1.12.2.jar                         | None                                     |
       | LCHIJA  | prehistoricspawns             | 2.0                  | [魔改]prehistoricspawns-2.1.jar                               | None                                     |
       | LCHIJA  | mdxlib                        | 3.0.0.26             | mdxlib-3.0.0.26.jar                                         | None                                     |
       | LCHIJA  | avp                           | 6.0.0.63             | aliensvspredator-6.0.0.63.jar                               | None                                     |
       | LCHIJA  | biometweaker                  | 3.2.369              | BiomeTweaker-1.12.2-3.2.369.jar                             | 631f326344f7f5fd7df7eb940760ebd52b7c9c17 |
       | LCHIJA  | calmdownzombieguy             | 1.0.0                | CalmDownZombieGuy-1.12.2-1.0.0.jar                          | None                                     |
       | LCHIJA  | denseneutroncollectors        | @VERSION@            | denseneutroncollectors-1.1.jar                              | None                                     |
       | LCHIJA  | gvclib                        | 1.12.2               | GVCLib__1.12.2__5.4.2.zip                                   | None                                     |
       | LCHIJA  | hmggirlfront                  | 1.12.2               | HMGDollsFrontLine1.12.2.β.22.1.zip                          | None                                     |
       | LCHIJA  | jeid                          | 1.0.3-57             | JustEnoughIDs-1.0.3-57.jar                                  | None                                     |
       | LCHIJA  | loadedmodsexporter            | 1.12.2-1.0           | loadedmodsexporter-1.12.2-1.0.jar                           | None                                     |
       | LCHIJA  | lttweaker                     | 1.1.14               | LootTableTweaker-1.12.2-1.1.14.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA  | mtrm                          | 1.2.2.30             | MineTweakerRecipeMaker-1.12.2-1.2.2.30 (1).jar              | None                                     |
       | LCHIJA  | mobstages                     | 2.0.8                | MobStages-1.12.2-2.0.8.jar                                  | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA  | mousetweaks                   | 2.10.1               | MouseTweaks-2.10.1-mc1.12.2.jar                             | None                                     |
       | LCHIJA  | nei                           | 2.4.3                | NotEnoughItems-1.12.2-2.4.3.245-universal.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA  | openterraingenerator          | v9.4                 | OpenTerrainGenerator-1.12.2-v9.4.jar                        | None                                     |
       | LCHIJA  | overpoweredarmorbar           | 0.3.2                | overpoweredarmorbar-1.12.2-0.3.2.jar                        | None                                     |
       | LCHIJA  | particleculling               | v1.3                 | particleculling-1.12.2-v1.3.1.jar                           | None                                     |
       | LCHIJA  | pntriassic                    | 1.0                  | pntriassic-1.12.2-1.0.jar                                   | None                                     |
       | LCHIJA  | potatooscustomstructureforhbm | 1.0.0                | Potatoo's+HBM+Structures_1.12.2-1.0.3.jar                   | None                                     |
       | LCHIJA  | prehistoricfloraintegration   | 2.01b                | prehistoricfloraintegration-1.12.2-2.01b.jar                | None                                     |
       | LCHIJA  | progressivebosses             | 1.5.4                | ProgressiveBosses-1.5.4-mc1.12.x.jar                        | None                                     |
       | LCHIJA  | scapeandrunvaccine            | 1.0.0                | srpvaccine-1.0.0.jar                                        | None                                     |
       | LCHIJA  | timemachine                   | 1.0                  | timemachine-1.0.jar                                         | None                                     |
       | LCHIJA  | tips                          | 1.0.9                | Tips-1.12.2-1.0.9.jar                                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA  | trailmix                      | 7.0.0                | TrailMix-1.12.2-7.0.0.jar                                   | None                                     |
       | LCHIJA  | tumbleweed                    | 1.12-0.4.7           | tumbleweed-1.12-0.4.7.jar                                   | None                                     |
       | LCHIJA  | vanillafix                    | 1.0.10-150           | VanillaFix-1.0.10-150.jar                                   | None                                     |
       | LCHIJA  | wailaharvestability           | 1.1.12               | WailaHarvestability-mc1.12-1.1.12.jar                       | None                                     |
       | LCHIJA  | wawla                         | 2.6.275              | Wawla-1.12.2-2.6.275.jar                                    | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA  | findme                        | 1.1.0                | 寻物findme-1.12.2-1.1.0-8.jar                                 | None                                     |
       | LCHIJA  | fastflyblockbreaking          | MC1.9.4-MC1.12.2-1.1 | 飞行破坏加快fastflyblockbreaking-MC1.9.4-MC1.12.2-1.1.jar         | None                                     |
       | LCHIJA  | jade                          | 0.1.0                | [玉 ] Jade-0.1.0.jar                                         | None                                     |
       | LCHIJA  | phosphor-lighting             | 1.12.2-0.2.6         | [磷] phosphor-1.12.2-0.2.6+build50-universal.jar             | f0387d288626cc2d937daa504e74af570c52a2f1 |
  Loaded coremods (and transformers): DLFMLCorePlugin ([动态光源]DynamicLights-1.12.2.jar)
                                        atomicstryker.dynamiclights.common.DLTransformer
                                      ParticleCullingLoadingPlugin (particleculling-1.12.2-v1.3.1.jar)
                                        
                                      OTGCorePlugin (OTG-Core.jar)
                                        com.pg85.otg.forge.asm.excluded.OTGClassTransformer
                                      MMFMLCorePlugin ([实用]MultiMine-1.12.2.jar)
                                        atomicstryker.multimine.common.fmlmagic.MMTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) ([优化]foamfix-0.10.15-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      CorePlugin (SmoothFont-mc1.12.2-2.1.4.jar)
                                        bre.smoothfont.asm.Transformer
                                      BiomeTweakerCore (BiomeTweakerCore-1.12.2-1.0.39.jar)
                                        me.superckl.biometweakercore.BiomeTweakerASMTransformer
                                      CoreMod ([前置]Aroma1997Core-1.12.2-2.0.0.2.jar)
                                        
                                      JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-57.jar)
                                        org.dimdev.jeid.JEIDTransformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      MekanismCoremod ([科技]Mekanism-1.12.2-9.8.3.390.jar)
                                        mekanism.coremod.KeybindingMigrationHelper
                                      ForgePlugin ([皮肤]CustomSkinLoader_Forge-14.9.jar)
                                        customskinloader.forge.TransformerManager
                                      HCASM ([前置]HammerLib-1.12.2-2.0.6.32.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      JechCore ([辅助-jei附属-拼音搜索]JustEnoughCharacters-1.12.0-3.4.7.jar)
                                        me.towdium.jecharacters.core.JechClassTransformer
                                      MixinBooter (!mixinbooter-7.0.jar)
                                        
                                      FMLModule (mdxlib-3.0.0.26.jar)
                                        com.asx.mdx.AccessTransformer
                                      PhosphorFMLLoadingPlugin ([磷] phosphor-1.12.2-0.2.6+build50-universal.jar)
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  HammerCore Debug Information: Dependent Mods:
                                -Improvable Skills (improvableskills) @ 12.4.68
  Patchouli open book context: n/a
  Armourer's Workshop: Baking Queue: 0
                       Request Queue: 0
                       Texture Paint Type: TEXTURE_REPLACE
                       Multipass Skin Rendering: true
                       Render Layers:
                        Render Class: nuparu.sevendaystomine.client.renderer.entity.RenderPlayerEnhanced
                       moe.plushie.armourers_workshop.client.render.entity.ModelResetLayer
                       net.minecraft.client.renderer.entity.layers.LayerBipedArmor
                       net.minecraft.client.renderer.entity.layers.LayerArrow
                       net.minecraft.client.renderer.entity.layers.LayerDeadmau5Head
                       net.minecraft.client.renderer.entity.layers.LayerCape
                       net.minecraft.client.renderer.entity.layers.LayerCustomHead
                       net.minecraft.client.renderer.entity.layers.LayerElytra
                       net.minecraft.client.renderer.entity.layers.LayerEntityOnShoulder
                       net.optifine.player.PlayerItemsLayer
                       nuparu.sevendaystomine.client.renderer.entity.LayerGuns
                       nuparu.sevendaystomine.client.renderer.entity.LayerClothing
                       nuparu.sevendaystomine.client.renderer.entity.LayerBackpack
                       com.tiviacz.travelersbackpack.client.render.LayerTravelersBackpack
                       gvclib.event.gun.LayerGunBase
                       moe.plushie.armourers_workshop.client.render.entity.SkinLayerRendererHeldItem
                       moe.plushie.armourers_workshop.client.render.entity.SkinLayerRendererPlayer
                       com.hbm.handler.JetpackHandler$JetpackLayer
                       me.ichun.mods.googlyeyes.common.layerrenderer.LayerGooglyEyes
                       me.ichun.mods.ichunutil.client.module.patron.LayerPatronEffect
                        Render Class: nuparu.sevendaystomine.client.renderer.entity.RenderPlayerEnhanced
                       moe.plushie.armourers_workshop.client.render.entity.ModelResetLayer
                       net.minecraft.client.renderer.entity.layers.LayerBipedArmor
                       net.minecraft.client.renderer.entity.layers.LayerArrow
                       net.minecraft.client.renderer.entity.layers.LayerDeadmau5Head
                       net.minecraft.client.renderer.entity.layers.LayerCape
                       net.minecraft.client.renderer.entity.layers.LayerCustomHead
                       net.minecraft.client.renderer.entity.layers.LayerElytra
                       net.minecraft.client.renderer.entity.layers.LayerEntityOnShoulder
                       net.optifine.player.PlayerItemsLayer
                       nuparu.sevendaystomine.client.renderer.entity.LayerGuns
                       nuparu.sevendaystomine.client.renderer.entity.LayerClothing
                       nuparu.sevendaystomine.client.renderer.entity.LayerBackpack
                       com.tiviacz.travelersbackpack.client.render.LayerTravelersBackpack
                       gvclib.event.gun.LayerGunBase
                       moe.plushie.armourers_workshop.client.render.entity.SkinLayerRendererHeldItem
                       moe.plushie.armourers_workshop.client.render.entity.SkinLayerRendererPlayer
                       com.hbm.handler.JetpackHandler$JetpackLayer
                       me.ichun.mods.googlyeyes.common.layerrenderer.LayerGooglyEyes
                       me.ichun.mods.ichunutil.client.module.patron.LayerPatronEffect
  Suspected Mods: Parasites Addon : OverLast (overlast)
  Profiler Position: N/A (disabled)
  Player Count: 0 / 8; []
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by acherlin** [comment]
测试时加入OTGmod，并没有发生崩溃问题，需要补充关于OTG参数的详细信息。另外从报错上来看可以通过关闭季节设定来暂时兼容这个问题。
