### ISSUE TITLE
Crashing with mobs from TF2 Stuff - Reloaded

### ISSUE THREAD

**Issue by num3raI** [acherlin/Parasites-Addon-OverLast#9]
[crash-2023-07-04_09.32.36-server.txt](https://github.com/acherlin/Parasites-Addon-OverLast/files/11943467/crash-2023-07-04_09.32.36-server.txt)

Happens with any TF2 mercenary.

**Comment by acherlin** [comment]
This error occurs when non-player entities kill Ancient Parasites with bullets. It will be fixed in the next version.
